### ISSUE TITLE
Heroku環境で spawn pdffonts  ENOENT でエラー

### ISSUE THREAD

**Issue by matt-note** [vibranthq/press-ready#17]
私が作成している「[IT勉強会用 名刺ジェネレーター](https://github.com/matt-note/it-benkyoukai-meishi-generator)」で Docker を使わずに press-ready を使うようにした時に、Heroku環境で`spawn pdffonts  ENOENT`でエラーとなってしまいました。このエラーを解消するには、どのようにすれば良さそうでしょうか？なお、ローカルでこのエラーは発生しませんでした。
よろしくお願いいたします。

![Screenshot from 2019-08-22 17-08-15](https://user-images.githubusercontent.com/39484102/63774066-69532c00-c917-11e9-9948-1bc128cf8f7b.png)

**Comment by uetchy** [comment]
press-readyを実行するシステムに`pdffonts`がインストールされている必要があります。`pdffonts`は`xpdf`パッケージに同梱されているので、buildpack等で`xpdf`を導入してみてください。

未検証ですが、[xpdfのbuildpack](https://elements.heroku.com/buildpacks/onode/heroku-buildpack-xpdf)がありました。試してみて、上手く動作したら是非コメントを残してください（Herokuで運用しようとしている他の方の助けになる可能性があります）

**Comment by matt-note** [comment]
> pdffontsはxpdfパッケージに同梱されているので、buildpack等でxpdfを導入してみてください。

ありがとうございます！
試した後に、またコメントを残していこうと思います。

**Comment by matt-note** [comment]
Heroku環境でxpdfのbuildpackを導入したところ、Heroku環境でpress-readyを使えるようになりました。アドバイス、ありがとうございました。
![Screenshot from 2019-08-29 03-53-25](https://user-images.githubusercontent.com/39484102/63939504-66387700-caa2-11e9-9076-87af1c814cc8.png)

xpdfのbuildpackは古くて動くものがなかったので、forkしたリポジトリを修正して動くようにしました。以下のbuildpackなら、Herokuでも動くはずです。
https://github.com/matt-note/heroku-xpdf-buildpack

**Comment by uetchy** [comment]
@matt-note 検証ありがとうございました👍
今後のために、READMEにフォークへのリンクを貼りました。
https://github.com/vibranthq/press-ready#advanced-usage

他に問題があれば新しくIssueを作成してください🌟
