### ISSUE TITLE
PDF/X-1a:2001のプロパティ情報

### ISSUE THREAD

**Issue by kmuto** [vibranthq/press-ready#2]
Acrobatのプリフライト検査に入れたところ、:2003と判断されてエラーになっていました。普通のPDF/X1a:2001の情報を見て以下のようにPDFX_def.psファイルを直したところ、検査に通るようになりました。

```
[ /GTS_PDFXVersion (PDF/X-1:2001) % Must be so (the standard requires).
  /GTS_PDFXConformance (PDF/X-1a:2001) % Must be so (the standard requires).
```
（PDFXVersionのaを削除。PDFXConformanceエントリを追加。）

**Comment by uetchy** [comment]
バグ修正までありがとうございます🤲
もし良ければPull Requestを送っていただけませんか？
（もちろん私が直接コミットしても良いですが、その場合authorが私になってしまい@kmutoさんのバグ修正のcontributionがGitHub上に正しく反映されないのが気になります）
