### ISSUE TITLE
グレースケール化

### ISSUE THREAD

**Issue by kmuto** [vibranthq/press-ready#3]
```
  -sProcessColorModel=DeviceGray \
  -sColorConversionStrategy=Gray \
  -sColorConversionStrategyForImages=Gray \
```
で` -sOutputICCProfile=${ICC_PROFILE_PATH} `はナシ、でK版のみのグレースケールにできます（使われるアルゴリズムは不明ですがそう変なものではなさそう）。
pdfxコマンドに切り替えフラグがほしくなりそうですね。

**Comment by uetchy** [comment]
グレースケール対応ありがとうございます！とても助かります。
デフォルトCMYK、コマンドラインオプションとしてGrayを提供すると良さそうです。
#4 と合わせてオプションを用意する必要性が高まってきたのでbashスクリプトから他の言語へ移行する予定です。
