### ISSUE TITLE
アウトライン化有無

### ISSUE THREAD

**Issue by kmuto** [vibranthq/press-ready#4]
フォントの中にType3や非埋め込みがなく、Type1/CIDの妥当なものだけであれば、アウトライン化の-dNoOutputFontsは付けない、というほうが通常は嬉しそうです（TeX組版の場合でType3が混じるケースはまずないですし、アウトライン化はいくぶん文字が太ります）。

**Comment by uetchy** [comment]
CSS組版（Chrome）のPDF出力を念頭に置いていたためこれまでは強制的にアウトライン化していましたが、Re:VIEWやその他組版ソフトの場合そのような問題は発生しないので、pdffontsの結果に応じて処理を分岐した方が良いですね。

**Comment by uetchy** [comment]
<img width="737" alt="Screen Shot 2019-04-11 at 16 52 10" src="https://user-images.githubusercontent.com/431808/55940325-d886f700-5c7a-11e9-9bad-41c852c871ef.png">
<img width="924" alt="Screen Shot 2019-04-11 at 16 56 46" src="https://user-images.githubusercontent.com/431808/55940337-df156e80-5c7a-11e9-8974-05d614b67005.png">
今後はアウトライン化するかどうかを自動で判別して、グレースケールはオプションで選択できるようになります。
